apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fl-client
spec:
  selector:
    matchLabels:
      app: fl-client
  template:
    metadata:
      labels:
        app: fl-client
    spec:
      containers:
      - name: fl-client
        image: river-client:latest
