apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flower-server
  template:
    metadata:
      labels:
        app: flower-server
    spec:
      containers:
      - name: flower-server
        image: river-server:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: flower-server
spec:
  selector:
    app: flower-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
